name: Build Unlocked

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 10 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}

    strategy:
      matrix:
        include:
          - otp: "27"
            elixir: "1.18"
          - otp: "27"
            elixir: "1.19"
          - otp: "28"
            elixir: "1.19"
          - otp: "29"
            elixir: "1.20"

    steps:
    - uses: actions/checkout@v7
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}
    - name: Restore dependencies cache
      uses: actions/cache@v6
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-otp${{ matrix.otp }}-elixir${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-otp${{ matrix.otp }}-elixir${{ matrix.elixir }}-
    - name: Unlock dependencies
      run: mix deps.unlock --all
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
